# Form implementation generated from reading ui file 'headerWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HeaderWidget(object):
    def setupUi(self, HeaderWidget):
        HeaderWidget.setObjectName("HeaderWidget")
        HeaderWidget.resize(951, 471)
        self.headerTable = QtWidgets.QTableWidget(parent=HeaderWidget)
        self.headerTable.setGeometry(QtCore.QRect(20, 20, 911, 431))
        self.headerTable.setShowGrid(False)
        self.headerTable.setObjectName("headerTable")
        self.headerTable.setColumnCount(3)
        self.headerTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.headerTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.headerTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.headerTable.setHorizontalHeaderItem(2, item)

        self.retranslateUi(HeaderWidget)
        QtCore.QMetaObject.connectSlotsByName(HeaderWidget)

    def retranslateUi(self, HeaderWidget):
        _translate = QtCore.QCoreApplication.translate
        HeaderWidget.setWindowTitle(_translate("HeaderWidget", "FITS Header"))
        item = self.headerTable.horizontalHeaderItem(0)
        item.setText(_translate("HeaderWidget", "Keyword"))
        item = self.headerTable.horizontalHeaderItem(1)
        item.setText(_translate("HeaderWidget", "Value"))
        item = self.headerTable.horizontalHeaderItem(2)
        item.setText(_translate("HeaderWidget", "Comment"))
